get http://127.0.0.1:5000/produk

### post
POST http://127.0.0.1:5000/produk
Content-Type: application/json

{
    "nama": "Jaket",
    "kategori": "Pakaian",
    "harga": "100.00",
    "stok": "25"
}